### ISSUE TITLE
Test cppcheck_QtTools_std fails on some machines

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#1]
Dear Maintainer,

I am packaging version 15.0 of Persalys on Debian, and while building in an amd64 chroot under Debian unstable, I get the following failure for cppcheck_QtTools_std:

18/22 Test #21: cppcheck_QtTools_std ..............................***Failed    0.26 sec
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pierre'
********* Start testing of PERSALYS::TestQtTools *********
Config: Using QtTest library 5.15.10, Qt 5.15.10 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 13.2.0), debian unknown
PASS   : PERSALYS::TestQtTools::initTestCase()
PASS   : PERSALYS::TestQtTools::testConversion()
FAIL!  : PERSALYS::TestQtTools::testSorting() 'listSorted == refSortedList' returned FALSE. (The string lists must be equal)
   Loc: [./lib/test/t_QtTools_std.cxx(69)]
PASS   : PERSALYS::TestQtTools::cleanupTestCase()
Totals: 3 passed, 1 failed, 0 skipped, 0 blacklisted, 3ms
********* Finished testing of PERSALYS::TestQtTools *********

Indeed, I printed listSorted and refSortedList, they are
listSorted = A1452 P1 P12 P2 P5 P890 X23
refSortedList = A1452 P1 P2 P5 P12 P890 X23

Still, if I build the test on my own amd64 machine with Debian testing and I run it, the test passes.

I guess there is some problem linked to numerical / alphanumeric comparison, but I am unsure. Please tell me if I can provide you with more information.

Thanks a lot,

-- 
Pierre

**Comment by jschueller** [comment]
it seems to depend on the locale: it will fail with the C locale
```
diff --git a/lib/src/model/QtTools.cxx b/lib/src/model/QtTools.cxx
index ac2f8173..12b9565e 100644
--- a/lib/src/model/QtTools.cxx
+++ b/lib/src/model/QtTools.cxx
@@ -182,7 +182,7 @@ QStringList QtOT::NaturalSorting(const QStringList& list)
   QStringList sorted = list;
 
   std::sort(sorted.begin(), sorted.end(), [=] (QString s1, QString s2) {
-       QCollator coll;
+       QCollator coll(QLocale::English);
        coll.setNumericMode(true);
        return coll.compare(s1, s2) < 0;
      });
```

**Comment by pgrt** [comment]
Hello @jschueller ,

You are right again, thanks! The issue has gone away with this change.

Best,

-- 
Pierre
