### ISSUE TITLE
MSVC: std::filesystem::filesystem_error

### ISSUE THREAD

**Issue by nitawa** [persalys/persalys#10]
Hi,
on Windows, in order to be able to compile Persalys with MSVC, one needs at this [line](https://github.com/persalys/persalys/blob/master/main/launcher.cxx#L111), one needs to replace
  `std::filesystem::filesystem_error` with   `fs::filesystem_error`

regards.

```
--- persalys-17.0.1_ref/main/launcher.cxx       2024-10-16 16:22:25.000000000 +0200
+++ persalys-17.0.1_dev/main/launcher.cxx       2024-11-21 11:35:26.000000000 +0100
@@ -108,7 +108,7 @@
     {
       fs::create_directories(pythonuserbase_dir / "Python312" / "site-packages");
     }
-    catch (const std::filesystem::filesystem_error &)
+    catch (const fs::filesystem_error &)
     {
     }
   }

```

**Comment by jschueller** [comment]
so you still need std::experimental for this compiler ?

**Comment by nitawa** [comment]
Oui. On doit migrer en visual version prochainement.

**Comment by jschueller** [comment]
La prochaine version de persalys est pour le mois de mars, ce sera bon d'ici là ?

**Comment by nitawa** [comment]
On pourra toujours compiler avec une version plus recente ce module. Pas de souci. Ici, pour être en coherence avec le define il faut appliquer le patch quz nous avons remonté.
Merci.

**Comment by YomGarcia** [comment]
Merci pour le retour ;)
