### ISSUE TITLE
Test pyinstallcheck_CouplingPhysicalModel_std fails on Debian unstable amd64

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#2]
Hello,

C++ tests are all passing on Debian unstable and amd64, I have failures for the Python tests. One is for CouplingPhysicalModel_std:

[CouplingPhysicalModel_std.txt](https://github.com/persalys/persalys/files/13209932/CouplingPhysicalModel_std.txt)

Thanks a lot for considering,

Best,

-- 
Pierre

**Comment by jschueller** [comment]
lets remove that test
[0005-CouplingPhysicalModel-Drop-clean-env-test.patch.txt](https://github.com/persalys/persalys/files/13214950/0005-CouplingPhysicalModel-Drop-clean-env-test.patch.txt)

**Comment by pgrt** [comment]
Hi @jschueller ,

Thanks for looking at my issue and proposing this solution.

Best,

Pierre
