### ISSUE TITLE
Test pyinstallcheck_DataModel_std fails on Debian unstable amd64

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#3]
Hello,

My last failure for Python tests is for DataModel_std:

[DataModel_std.txt](https://github.com/persalys/persalys/files/13209973/DataModel_std.txt)

The repeated error message is raised from an OpenTURNS piece of code, and it suggests -- together with the very last line -- there is some locale issue here? The csv file that is read indeed uses commas as the decimal separator.

Thanks a lot,

-- 
Pierre

**Comment by jschueller** [comment]
yes, that part of the test also depends on the fr locale

**Comment by jschueller** [comment]
[0004-DataModel-Fix-test-without-fr-locale.patch.txt](https://github.com/persalys/persalys/files/13214971/0004-DataModel-Fix-test-without-fr-locale.patch.txt)

**Comment by pgrt** [comment]
HI @jschueller ,

Thanks a lot for the fix!

Now the test passes, only the comparison to expected output fails:

--- /<<PKGBUILDDIR>>/python/test/t_DataModel_std.expout 2023-10-19 13:20:18.000000000 +0000
+++ /<<PKGBUILDDIR>>/builddir/python/test/t_DataModel_std.out   2023-10-31 12:01:20.140153569 +0000
@@ -834,4 +834,3 @@
 aDataAnalysis = persalys.DataAnalysis('aDataAnalysis', myDataModel)
 myStudy.add(aDataAnalysis)
 
-[Année,Débit mesuré maximal (m3/s),Hauteur mesurée (m),Prévision modèle,Ecart donnée-modèle,H complet]

For sure I can ignore the comparison to expout, I let you see if you prefer changing the expected output or also ignoring the comparison in Persalys.

Best,

Pierre

**Comment by jschueller** [comment]
[0004-DataModel-Fix-test-without-fr-locale.patch.txt](https://github.com/persalys/persalys/files/13216222/0004-DataModel-Fix-test-without-fr-locale.patch.txt)
