### ISSUE TITLE
Testing the equality of distributions should be done with assert_almost_equal

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#4]
Hello,

In OpenTURNS, following https://github.com/openturns/openturns/issues/2179 and https://github.com/openturns/openturns/issues/2181, a function assert_almost_equal has been created to compare distributions and allow one to identify distributions even if they fail tests like
`(k_ == other.k_) && (lambda_ == other.lambda_) && (gamma_ == other.gamma_)`
for numerical reasons.

I think we should also use such assert_almost_equal function in the tests of Persalys. There is at least an issue with cppcheck_ProbabilisticModelWindow_std, in which we have the line
`QVERIFY2(model->getInputs()[3].getDistribution() == OT::Gamma(100, 50), "wrong input distribution");`
which relies on the == operator. I got a failure again yesterday (https://buildd.debian.org/status/fetch.php?pkg=persalys&arch=arm64&ver=15.0%2Bds-1&stamp=1698779423&raw=0) and it is because the == operator of Gamma was applied to
`Gamma(k = 100, lambda = 50, gamma = -1.11022e-16)` and `Gamma(k = 100, lambda = 50, gamma = 0)`.

Using assert_almost_equal would solve my concern. Personally I think we should test whether the parameters are close enough when redefining ==, instead of comparing doubles with ==, as (as we can see here) there are good reasons for which parameters may differ a bit. The two distributions quoted above are obviously the same ones. Still, I know there has been quite a debate on this, so the "assert_almost_equal" solution sounds reasonable :-)

Best,

-- 
Pierre

**Comment by jschueller** [comment]
yes, using assert_almost equal is better, tell me if this works:
[0001-ProbabilisticModelWindow-Use-assert_almost_equal.patch.txt](https://github.com/persalys/persalys/files/13235888/0001-ProbabilisticModelWindow-Use-assert_almost_equal.patch.txt)

**Comment by pgrt** [comment]
Hi,

Thanks! I have not forgotten the patch to test, I am just waiting for a slot for transitioning from libopenturns0.21 to 0.22 in Debian/unstable, then I will tell you!

Best,

-- 
Pierre

**Comment by pgrt** [comment]
Hi again,

I can now say it works!

Still the last before the last addition has to be removed, else the problematic test remains. Like in this file, which is your one + the removed line:
[0001-ProbabilisticModelWindow-Use-assert_almost_equal.patch.txt](https://github.com/persalys/persalys/files/13322476/0001-ProbabilisticModelWindow-Use-assert_almost_equal.patch.txt)

Thanks again!

-- 
Pierre

**Comment by jschueller** [comment]
> Still the last before the last addition has to be removed

this is unclear, do you mean it still asserts with my patch ? at what line ?

**Comment by pgrt** [comment]
Hmm sorry, my sentence got much confused :-D

I was meaning there was still
`QVERIFY2(model->getInputs()[3].getDistribution() == OT::Gamma(100, 52), "wrong input distribution");`
on line 176 although you had added
`OT::Test::assert_almost_equal(model->getInputs()[3].getDistribution(), OT::Gamma(100.0, 52.0), 1e-5, 1e-8, "wrong input distribution");`
just afterwards. Because of this remaining == test, I still got failures.

**Comment by jschueller** [comment]
oh ok, got it

**Comment by jschueller** [comment]
we applied all in our gitlab
