### ISSUE TITLE
References for the Python tests have to be updated for Openturns 1.23

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#5]
Hello,

The *.expout files of the tests
- SymbolicPhysicalModel
- FORMAnalysis
- SORMAnalysis
- FORMImportanceSamplingAnalysis
- CalibrationAnalysis
- FunctionalChaosAnalysis

have to be updated after the changes in OT 1.23, e.g. because of the renaming  ComposedDistribution -> JointDistribution.
Concerning the last one, the reference should incorporate two last lines with "is least squares" and "is model selection", which are now printed by lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosResult.cxx in OT.

Enclosed is the extract of the build log emphasizing the discrepancies due to OT 1.22 -> OT 1.23.

[extract_new_names.log](https://github.com/user-attachments/files/15839700/extract_new_names.log)

**Comment by jschueller** [comment]
this is done already in our side for 16.1

**Comment by pgrt** [comment]
Thanks!
I looked for recent commits addressing this in this repo but did not find any, hence my issue. But all fine then :)
