### ISSUE TITLE
Differences in output of Python tests wrt expout references, related to number of calls

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#6]
Hello,

When building persalys against OT 1.23, I got two errors due to differences between test outputs and references in *.expout files.

Unlike in Issue #5, I don't think these differences are linked to changes in the OT interface, as they are related to (I guess) numbers of function calls.
Enclosed is the relevant part of the build log. The faulty tests are:
- CouplingPhysicalModel
- FileMemoizeFunction

[extract_calls_counts.log](https://github.com/user-attachments/files/15839808/extract_calls_counts.log)

Is it safe to skip the comparison to *.expout for these two tests?

Thanks,

Pierre

**Comment by jschueller** [comment]
yes, just skip the tests

**Comment by jschueller** [comment]
@pgrt the new version 16.1 should fix most problems

**Comment by pgrt** [comment]
Thanks @jschueller , that's right! Version 16.1 has reached Debian/unstable and builds there.

Best,
Pierre
