### ISSUE TITLE
CentOS 8  Stream and usr/include/tbb/tbb_profiling.:34: Parse error at "/usr/include/tbb/internal/_tbb_strings.h"

### ISSUE THREAD

**Issue by nitawa** [persalys/persalys#745]
Hi,
wondering whether someone tried to compile PERSALYS v12.0  on CentOS 8  Stream:
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOSStream
Description:	CentOS Stream release 8
Release:	8
Codename:	n/a

```
with:
```
qt 5.15.3-1.el8
qwt-qt5-devel.x86_64 6.1.5-5.el8
tbb-devel.x86_64  2018.2-9.el8   
```
The issue seems to be known:
[https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6014884.html](https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6014884.html)
[https://bugreports.qt.io/browse/QTBUG-80990](https://bugreports.qt.io/browse/QTBUG-80990)

Note that it works if one uses qt 5.15.2-1.el8
```
[ 35%] Generating persalys/moc_EditableExportableTableView.cpp
[ 35%] Generating persalys/moc_ExportableTableView.cpp
[ 35%] Generating persalys/moc_HorizontalHeaderViewWithCombobox.cpp
usr/include/tbb/tbb_profiling.:34: Parse error at "/usr/include/tbb/internal/_tbb_strings.h"
make[2]: *** [lib/src/view/utils/CMakeFiles/persalysutils.dir/build.make:174: lib/src/view/utils/persalys/moc_EditValuesWizard.cpp] Error 1
make[2]: *** Attente des tâches non terminées....
make[1]: *** [CMakeFiles/Makefile2:803: lib/src/view/utils/CMakeFiles/persalysutils.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

```
Do you know whether there is some patch which could be applied at PERSALYS level ?
Thanks

**Comment by jschueller** [comment]
not really much to do here besides patching manually tbb_profiling.h with guarding Q_MOC_RUN or disabling tbb in openturns,
this will disappear in v13 since tbb become a private dependency of openturns
closing since this is an upstream bug
