### ISSUE TITLE
Failing test due to a Locale error

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#747]
Hello,

In order to have a succeeding build, I had to remove the Python test DataModel_std as it was failing on my amd64 machine running Debian 12, with

 Traceback (most recent call last):
   File "/build/persalys-aWJWdD/persalys-12.0.1+ds/python/test/t_DataModel_std.py", line 90, in <module>
     model = persalys.DataModel('myDataModel2', filename, inColumns)
   File "/usr/lib/python3/dist-packages/persalys/persalys.py", line 6696, in __init__
     _persalys.DataModel_swiginit(self, _persalys.new_DataModel(*args))
 RuntimeError: InternalException : Locale not available

I will be happy to perform further tests on this issue if you want.

Best regards,

Pierre

**Comment by jschueller** [comment]
this test assumed the fr locale to be available for a csv with comma as decimal separator,
this is fixed now
