### ISSUE TITLE
Minor spelling issue : algoritm

### ISSUE THREAD

**Issue by pgrt** [persalys/persalys#749]
Hello,

Just a quick notice that "algorithm" is mispelled as "algoritm" in the doc, see enclosed patch.

Best,
Pierre
[spelling.txt](https://github.com/persalys/persalys/files/10266556/spelling.txt)

**Comment by jschueller** [comment]
thanks, applied

**Comment by jschueller** [comment]
which command can I run to detect these ?

**Comment by pgrt** [comment]
Hi!

Thanks for addressing my issue.

There is a list of common spelling mistakes in Lintian, the Debian linter. I ran it from the unpacked source tree of the openturns package:
`lintian -i -I`

Hope this helps!

Best,
Pierre
